#!/usr/bin/env bash
#
# Fetch the ONNX face models this service runs on, and verify them.
#
# Model weights are executable inputs — they decide who gets verified as whom.
# They are therefore checksum-pinned against a committed manifest and the
# download fails closed on any mismatch.
#
#   ./scripts/download_models.sh              fetch + verify the default set
#   ./scripts/download_models.sh --verify     verify what is on disk, fetch nothing
#   ./scripts/download_models.sh --record     fetch, then (re)write the manifest
#   ./scripts/download_models.sh --with-insightface
#                                             also fetch the opt-in buffalo_l set
#
# Env overrides: MODEL_DIR, OPENCV_ZOO_REF, WITH_INSIGHTFACE=1,
#                ACCEPT_NONCOMMERCIAL_LICENSE=1
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

MODEL_DIR="${MODEL_DIR:-${ROOT_DIR}/models}"
MANIFEST="${SCRIPT_DIR}/models.sha256"

# Pinned to a commit, never to a branch. "version every model" is meaningless
# if the bytes behind the name 2023mar can change underneath you.
OPENCV_ZOO_REF="${OPENCV_ZOO_REF:-47534e27c9851bb1128ccc0102f1145e27f23f98}"
ZOO_BASE="https://github.com/opencv/opencv_zoo/raw/${OPENCV_ZOO_REF}/models"

INSIGHTFACE_URL="https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip"

WITH_INSIGHTFACE="${WITH_INSIGHTFACE:-0}"
MODE="fetch"

# --- default model set: detector + recogniser, both permissively licensed ----
# Format: "<relative-dest>|<url>"
DEFAULT_MODELS=(
  "face_detection_yunet_2023mar.onnx|${ZOO_BASE}/face_detection_yunet/face_detection_yunet_2023mar.onnx"
  "face_recognition_sface_2021dec.onnx|${ZOO_BASE}/face_recognition_sface/face_recognition_sface_2021dec.onnx"
)

# --- output -----------------------------------------------------------------
if [ -t 1 ]; then
  C_RED=$'\033[31m'; C_GRN=$'\033[32m'; C_YEL=$'\033[33m'; C_DIM=$'\033[2m'; C_OFF=$'\033[0m'
else
  C_RED=''; C_GRN=''; C_YEL=''; C_DIM=''; C_OFF=''
fi
info() { printf '%s\n' "$*"; }
ok()   { printf '%s  ok%s  %s\n' "${C_GRN}" "${C_OFF}" "$*"; }
warn() { printf '%s warn%s %s\n' "${C_YEL}" "${C_OFF}" "$*" >&2; }
die()  { printf '%sfail%s  %s\n' "${C_RED}" "${C_OFF}" "$*" >&2; exit 1; }

usage() { sed -n '2,22p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0; }

# --- portable helpers (macOS and Linux) -------------------------------------
sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}'
  elif command -v shasum   >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print $1}'
  else die "need sha256sum or shasum on PATH"; fi
}

size_of() {
  if stat -f%z "$1" >/dev/null 2>&1; then stat -f%z "$1"   # BSD / macOS
  else stat -c%s "$1"; fi                                   # GNU / Linux
}

# --- integrity gates --------------------------------------------------------

# opencv_zoo stores .onnx files in Git LFS. The raw URL normally redirects to
# the real object, but on a rate-limit or a bad ref it returns a ~130-byte text
# pointer instead. Without this check the failure surfaces much later as a
# baffling `cv2.error: (-2:Unspecified error) FAILED: fs.is_open()` at startup.
assert_not_lfs_pointer() {
  local f="$1" bytes
  bytes="$(size_of "$f")"
  if [ "${bytes}" -lt 102400 ] && head -c 64 "$f" | LC_ALL=C grep -q 'git-lfs'; then
    rm -f "$f"
    die "$(basename "$f"): got a Git LFS pointer (${bytes} bytes), not the model.
      The ref may be wrong or GitHub is rate-limiting. Retry, or set
      OPENCV_ZOO_REF to a commit you know carries the weights."
  fi
}

# An ONNX file is a protobuf whose first field is ir_version (field 1, varint)
# => the first byte is 0x08. Cheap structural check that catches an HTML error
# page or a truncated download before cv2 ever sees it.
assert_onnx_magic() {
  local f="$1" first
  first="$(head -c 1 "$f" | od -An -tx1 | tr -d ' \n')"
  [ "${first}" = "08" ] || die "$(basename "$f"): not an ONNX protobuf (first byte 0x${first:-??})"
}

fetch() {
  local dest="$1" url="$2"
  if [ -f "${dest}" ]; then
    info "${C_DIM}have${C_OFF}  $(basename "${dest}")"
    return 0
  fi
  info "${C_DIM}get${C_OFF}   $(basename "${dest}")"
  curl -fSL --retry 3 --retry-delay 2 --progress-bar "${url}" -o "${dest}.part" \
    || { rm -f "${dest}.part"; die "download failed: ${url}"; }
  mv "${dest}.part" "${dest}"
  assert_not_lfs_pointer "${dest}"
  assert_onnx_magic "${dest}"
}

# --- manifest ---------------------------------------------------------------
record_manifest() {
  {
    echo "# Checksum manifest for the ONNX face models."
    echo "#"
    echo "# Generated by scripts/download_models.sh --record. Regenerate ONLY when"
    echo "# deliberately changing models, and eyeball the sizes before committing:"
    echo "#   yunet ~232 KB, sface ~37 MB, det_10g ~16.9 MB, w600k_r50 ~166 MB."
    echo "#"
    echo "# opencv_zoo ref: ${OPENCV_ZOO_REF}"
    echo "#"
    echo "# <sha256>  <bytes>  <path relative to models/>"
    ( cd "${MODEL_DIR}" && find . -name '*.onnx' -type f | sed 's|^\./||' | sort ) \
    | while read -r rel; do
        printf '%s  %s  %s\n' "$(sha256_of "${MODEL_DIR}/${rel}")" \
                              "$(size_of "${MODEL_DIR}/${rel}")" "${rel}"
      done
  } > "${MANIFEST}"
  ok "wrote $(basename "${MANIFEST}")"
  grep -v '^#' "${MANIFEST}" | sed 's/^/      /'
}

verify_manifest() {
  [ -f "${MANIFEST}" ] || die "no manifest at ${MANIFEST} — run with --record first"
  local failed=0 checked=0 rel want_sha want_bytes got_sha got_bytes
  while read -r want_sha want_bytes rel; do
    [ -n "${rel:-}" ] || continue
    local f="${MODEL_DIR}/${rel}"
    if [ ! -f "${f}" ]; then
      # buffalo_l is opt-in; absence is not a failure unless it was requested.
      case "${rel}" in
        insightface/*) [ "${WITH_INSIGHTFACE}" = "1" ] || { info "${C_DIM}skip${C_OFF}  ${rel} (opt-in, not fetched)"; continue; } ;;
      esac
      warn "missing: ${rel}"; failed=1; continue
    fi
    got_sha="$(sha256_of "${f}")"; got_bytes="$(size_of "${f}")"
    checked=$((checked + 1))
    if [ "${got_sha}" != "${want_sha}" ]; then
      warn "CHECKSUM MISMATCH ${rel}"
      warn "  expected ${want_sha}"
      warn "  actual   ${got_sha}"
      failed=1
    elif [ "${got_bytes}" != "${want_bytes}" ]; then
      warn "size mismatch ${rel}: expected ${want_bytes}, got ${got_bytes}"; failed=1
    else
      ok "${rel}  ${got_bytes} bytes  ${got_sha:0:16}…"
    fi
  done < <(grep -v '^#' "${MANIFEST}")

  [ "${failed}" -eq 0 ] || die "verification failed — do NOT run the service against these files"
  [ "${checked}" -gt 0 ] || die "manifest matched no files on disk"
  ok "${checked} model(s) verified against the manifest"
}

# --- opt-in, non-commercially licensed set ----------------------------------
fetch_insightface() {
  local dest_dir="${MODEL_DIR}/insightface/buffalo_l"
  if [ -f "${dest_dir}/w600k_r50.onnx" ] && [ -f "${dest_dir}/det_10g.onnx" ]; then
    info "${C_DIM}have${C_OFF}  buffalo_l (det_10g, w600k_r50)"
    return 0
  fi

  cat >&2 <<'NOTICE'

  ┌─ LICENCE NOTICE ───────────────────────────────────────────────────────┐
  │ InsightFace buffalo_l pretrained weights are licensed for              │
  │ NON-COMMERCIAL RESEARCH USE ONLY.                                      │
  │                                                                        │
  │ In this service they are benchmark-only: the adapter is refused at     │
  │ startup when ENV=prod unless ALLOW_NONCOMMERCIAL_MODELS is set, and    │
  │ these files are never baked into a distributable image.                │
  │                                                                        │
  │ The default YuNet + SFace path is permissively licensed and needs      │
  │ none of this.                                                          │
  └────────────────────────────────────────────────────────────────────────┘

NOTICE

  if [ "${ACCEPT_NONCOMMERCIAL_LICENSE:-0}" != "1" ]; then
    if [ -t 0 ]; then
      read -r -p "  Proceed and download these weights? [y/N] " reply
      case "${reply}" in [yY]*) ;; *) die "declined — buffalo_l not downloaded" ;; esac
    else
      die "non-interactive: set ACCEPT_NONCOMMERCIAL_LICENSE=1 to consent"
    fi
  fi

  command -v unzip >/dev/null 2>&1 || die "need unzip on PATH for the buffalo_l bundle"
  mkdir -p "${dest_dir}"
  local tmp; tmp="$(mktemp -d)"
  trap 'rm -rf "${tmp}"' RETURN

  info "${C_DIM}get${C_OFF}   buffalo_l.zip (~281 MB)"
  curl -fSL --retry 3 --retry-delay 2 --progress-bar "${INSIGHTFACE_URL}" -o "${tmp}/buffalo_l.zip" \
    || die "download failed: ${INSIGHTFACE_URL}"
  unzip -q -o -j "${tmp}/buffalo_l.zip" -d "${tmp}/x"

  # The bundle also ships genderage / 2d106det / w600k_r50 variants this
  # service does not use. Keep only the two we actually load.
  local m
  for m in det_10g.onnx w600k_r50.onnx; do
    [ -f "${tmp}/x/${m}" ] || die "buffalo_l bundle did not contain ${m}"
    mv "${tmp}/x/${m}" "${dest_dir}/${m}"
    assert_onnx_magic "${dest_dir}/${m}"
    ok "buffalo_l/${m}  $(size_of "${dest_dir}/${m}") bytes"
  done
}

# --- args -------------------------------------------------------------------
while [ $# -gt 0 ]; do
  case "$1" in
    --verify)           MODE="verify" ;;
    --record)           MODE="record" ;;
    --with-insightface) WITH_INSIGHTFACE=1 ;;
    -h|--help)          usage ;;
    *)                  die "unknown argument: $1 (try --help)" ;;
  esac
  shift
done

# --- run --------------------------------------------------------------------
mkdir -p "${MODEL_DIR}"
info "model dir: ${MODEL_DIR}"
info "zoo ref:   ${OPENCV_ZOO_REF}"
info ""

if [ "${MODE}" != "verify" ]; then
  for entry in "${DEFAULT_MODELS[@]}"; do
    fetch "${MODEL_DIR}/${entry%%|*}" "${entry#*|}"
  done
  [ "${WITH_INSIGHTFACE}" = "1" ] && fetch_insightface
  info ""
fi

case "${MODE}" in
  record) record_manifest ;;
  *)      verify_manifest ;;
esac

info ""
ok "models ready"
